#!/bin/bash

git stash -q --keep-index

echo "Running git pre-commit hook"

./gradlew ktlintMainSourceFormat

RESULT=$?

git stash pop -q

#return 1 exit code if running check fails
[ $RESULT -ne 0 ] && exit 1
exit 0